baseurl = "/"
languageCode = "en-us"
theme = "terminal-ban"

[pagination]
  pagerSize = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  #
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "yellow"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 11

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  favicon = "bananominer_pickaxe.png"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.en]
    languageName = "English"
    title = "Bananocraft"
    subtitle = "Banano + Minecraft = Bananocraft"
    keywords = "Banano Minecraft Akash IPFS storj web3"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Bananocraft"
      logoHomeLink = "/"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/posts/about"
    [[languages.en.menu.main]]
      identifier = "cheatsheet"
      name = "Cheatsheet"
      url = "/cheatsheet"
    [[languages.en.menu.main]]
      identifier = "quickstart"
      name = "Quickstart"
      url = "/quickstart"
    [[languages.en.menu.main]]
      identifier = "servers"
      name = "Servers"
      url = "/servers"
    [[languages.en.menu.main]]
      identifier = "rules"
      name = "Rules"
      url = "/rules"
    [[languages.en.menu.main]]
      identifier = "showcase"
      name = "Showcase"
      url = "/showcase"
    [[languages.en.menu.main]]
      identifier = "upkeep"
      name = "Upkeep"
      url = "/upkeep"
    [[languages.en.menu.main]]
      identifier = "discord"
      name = "Discord"
      url = "/discord"
    [[languages.en.menu.main]]
      identifier = "feed"
      name = "Live Feed"
      url = "/feed"
    [[languages.en.menu.main]]
      identifier = "leaderboard"
      name = "Leaderboard"
      url = "/leaderboard"
