name = "bananocraft-feed"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Create this with: wrangler kv namespace create FEED_KV
# Then paste the id below
kv_namespaces = [
  { binding = "FEED_KV", id = "b2d204539676479d980a38cdd9afa067" }
]

# Route to feed.bananocraft.cc
routes = [
  { pattern = "feed.bananocraft.cc/*", zone_name = "bananocraft.cc" }
]

# Or use a workers.dev subdomain during testing:
# workers_dev = true
